# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FreeAnimal' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FreeAnimal
  
  pod 'Alamofire'
  pod 'AlamofireImage'
  pod 'SwipeView'
  pod 'Lightbox'
  pod 'SVProgressHUD'

  target 'FreeAnimalTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FreeAnimalUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
